blank_issues_enabled: false
contact_links:
  - name:  Documentaci贸n del Proyecto
    url: https://github.com/fede-r1c0/homelab#readme
    about: Consulta la documentaci贸n completa del proyecto
  - name:  Gu铆a de Contribuci贸n
    url: https://github.com/fede-r1c0/homelab/blob/main/CONTRIBUTING.md
    about: Aprende c贸mo contribuir al proyecto
  - name:  Documentaci贸n T茅cnica
    url: https://github.com/fede-r1c0/homelab/tree/main/docs
    about: Accede a la documentaci贸n t茅cnica detallada
